apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-upstream
  labels:
    app: go-upstream
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-upstream
  template:
    metadata:
      labels:
        app: go-upstream
    spec:
      containers:
        - name: go-upstream
          image: go-upstream:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
          env:
            - name: GRACEFUL
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: go-upstream
spec:
  selector:
    app: go-upstream
  ports:
    - port: 7000
      targetPort: 7000
  type: ClusterIP
